dist: xenial
sudo: required
language: node_js
node_js:
  - v12

sudo: true
services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    - POSTGRES_USER=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_DB=travis_ci_test
    - NODE_ENV="test"
    - PGPORT=5432
    - PGUSER=postgres
    - CI=false

cache:
  npm: false
